isProd: ${IS_PROD:false}

server:
  port: ${PORT:8082}

spring:
  application:
    name: riot-api
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      discovery:
        prefer-ip-address: true

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true