isProd: false

server:
  port: 8082

token:
  # 60 min
  expirationTime: 3600000
  secret: veryhardsecret

my:
  swagger:
    prefix:

spring:
  application:
    name: riot-api
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

# Show details of health endpoint
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

feign:
  httpclient:
    connection-timeout: 60000
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000


---
spring:
  profiles: prod

my:
  swagger:
    prefix: /riot-api

isProd: true