apiVersion: apps/v1
kind: Deployment
metadata:
  name: riot-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: riot-api
    spec:
      containers:
        - image: blarc/rso-riotapi:f388814
          name: riot-api
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
            initialDelaySeconds: 90
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 90
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: riot-api
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: riot-api