name: Riot API

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Test with Maven
        run: mvn -B test --file pom.xml
      - name: Package with Maven
        run: mvn -DIS_PROD=true package -B --file pom.xml
      - name: Build a Docker image
        run: |
          mkdir target/dependency
          (cd target/dependency; jar -xf ../*.jar)
          docker build . -t blarc/rso-riotapi:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image to Docker Hub
        run: docker push blarc/rso-riotapi:latest