name: Riot API

on:
  push:
    branches: [ dev ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Test with Maven
        run: mvn -B test --file pom.xml